# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19ca2665f83b6723efc1077132a4cc666ecd6ac6b1e5f7884595e08514d1f457da14b441090ab64aed03f5f37972325c8640fb96d552459f861dc655dbb31d61

test:
  secret_key_base: edf47134a5638cb70a7c93d657277427dc05113710482af2aefd0efe8409590be76606409ee1ad388140c4b417c42fad667b75b62450dcc58823bbb63e282e6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
